---
title: Promise 对象
comments: true
description: Promise 对象
tags: "ES6"
date: 2017-08-29 11:23:29
categories: "ES6"
keywords: ES6, Promise
---

Promise 是异步编程的一种解决方案，比传统的解决方案——回调函数和事件——更合理和更强大。Promise 是一个对象，从它可以获取异步操作的消息。

Promise对象是一个构造函数，用来生成Promise实例。

```js
const promise = new Promise((resolve,reject)=>{
//do something
})
console.log(promise,typeof promise)   //Promise, "object"
```

Promise构造函数接受一个函数作为参数，该函数的两个参数分别是`resolve`和`reject`。

- resolve函数的作用是，将Promise对象的状态从“未完成”变为“成功”，在异步操作成功时调用，并将异步操作的结果，作为参数传递出去。

- reject函数的作用是，将Promise对象的状态从“未完成”变为“失败”，在异步操作失败时调用，并将异步操作报出的错误，作为参数传递出去。

Promise实例生成以后，可以用`then`方法分别指定`resolved`状态和`rejected`状态的回调函数。

```js
promise.then(value=>{
    console.log('success')
},error=>{
    console.log('fail')
})
```

`then`方法可以接受两个回调函数作为参数。第一个回调函数是Promise对象的状态变为`resolved`时调用，第二个回调函数是Promise对象的状态变为`rejected`时调用。其中，第二个函数是可选的，不一定要提供。这两个函数都接受Promise对象传出的值作为参数。

```js
function settimeout(ms){
    return new Promise((resolve,reject)=>{
        setTimeout(resolve,ms,'done')
    })
}
settimeout(100).then(value=>{
    console.log(value)   //done
})
```

`timeout`方法返回一个Promise实例，过了指定的时间（ms参数）以后，Promise实例的状态变为`resolved`，就会触发`then`方法绑定的回调函数。

```js
const promise = new Promise((resolve,reject)=>{
    resolve('success')
    console.log('next')
}).then(value=>console.log(value))
console.log('last')
// first   next  last  success
```

Promise 新建后立即执行，首先输出 `first`，`next`，`then`方法指定的回调函数，将在当前脚本所有同步任务执行完才会执行，所`last`先输出，`success`最后输出。

### Promise.prototype.then()

Promise 实例具有`then`方法，也就是说，`then`方法是定义在原型对象`Promise.prototype`上的。它的作用是为 Promise 实例添加状态改变时的回调函数。前面说过，`then`方法的第一个参数是`resolved`状态的回调函数，第二个参数（可选）是`rejected`状态的回调函数。

`then`方法返回的是一个新的`Promise`实例（注意，不是原来那个Promise实例）。因此可以采用链式写法，即`then`方法后面再调用另一个`then`方法。

### Promise.prototype.catch()

`Promise.prototype.catch`方法是`.then(null, rejection)`的别名，用于指定发生错误时的回调函数。

Promise 在`resolve`语句后面，再抛出错误，不会被捕获，等于没有抛出。因为 Promise 的状态一旦改变，就永久保持该状态，不会再变了。

建议总是使用`catch`方法，而不使用then方法的第二个参数。

```js
const promise = new Promise((resolve,reject)=>{
    console.log('first')
    resolve('success')
    console.log('next')
})
//不推荐这样写
promise.then(value=>{
    console.log('success')
},error=>{
    console.log('fail')
})
//推荐这样写：
.then(value=>console.log(value))
.catch(error=>{
    console.log(error)
})
```

跟传统的`try/catch`代码块不同的是，如果没有使用catch方法指定错误处理的回调函数，Promise 对象抛出的错误不会传递到外层代码，即不会有任何反应。

```js
const  promise = function (){
return new Promise((resolve,reject)=>{
        console.log(x+2)
    })
}
promise().then(value=>{
    console.log('done')
})
setTimeout(()=>console.log('123'),1000)
// Uncaught (in promise) ReferenceError: x is not defined
// 123
```

### Promise.prototype.finally()

finally方法用于指定不管 Promise 对象最后状态如何，都会执行的操作。

```js
const  promise = new Promise((resolve,reject)=>{
        resolve()
    })
    .then(value=>{console.log('done')})
    .catch(error=>console.log('error'))
    .finally((res)=>console.log('finally'))
//done
//finally
```

### Promise.all()，Promise.race()，Promise.resolve()

`Promise.all`方法用于将多个 Promise 实例，包装成一个新的 Promise 实例。

```js
const[foo,bar] = [new Promise((resolve,reject)=>{}),new Promise((resolve,reject)=>{})]
const foobar = Promise.all([foo,bar])
console.log(foobar)   //Promise {<pending>}
```

`Promise.all`方法接受一个数组作为参数（Promise.all方法的参数可以不是数组，但必须具有 `Iterator` 接口，且返回的每个成员都是 Promise 实例），`foo`,`bar`都是 Promise 实例。


`foobar`的状态以及`Promise.race()`，`Promise.resolve()`可以参考这里[promise](http://es6.ruanyifeng.com/#docs/promise)

### Promise.reject()

`Promise.reject(reason)`方法也会返回一个新的 Promise 实例，该实例的状态为rejected。

```js
const promise = Promise.reject('error')
   .then(null,error=>console.log(error))   //error
//等同于
const pro = new Promise((resolve,reject)=>reject('error'))
.then(null,error=>console.log(error))   //error
```